### ISSUE TITLE
Where does RestClient come from?

### ISSUE THREAD

**Issue by takichin** [rfunduk/rails-stripe-connect-example#12]
Hi rfunduk, thank you for your example.

I want to know that where "RestClient" is coming from in the below code.

gem "oauth2"??

rails-stripe-connect-example/app/services/stripe_oauth.rb
```ruby
...
response = RestClient.get url
      # If the request was successful, then we're all good to return
      # this URL.
...
```

**Comment by rfunduk** [comment]
No worries I hope you find it useful!

`rest-client` is a dependency of `stripe`

https://github.com/rfunduk/rails-stripe-connect-example/blob/master/Gemfile.lock#L142-L144

It might have been a good idea to explicitly make it a dependency in `Gemfile`, I'll give you that :)
