### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by dcflow** [rfunduk/rails-stripe-connect-example#2]
Hi Ryan,

First, thank you for this amazing app. I am trying to adopt it to an iOS app and do you think this is possible: After authenticating the user, sending a url to the server like this http://localhost:3000/payment?buyer_id=...&seller_id=...&amount=...&fee=... with the buyer, seller id and the amount and the server would make the payment with stripe and return the other parameters.  This would remove a lot of steps. 

Thank you!

**Comment by rfunduk** [comment]
Hey, glad you're finding this project useful! I don't see any problem with the approach you're suggesting. I might try to keep the `amount` and `fee` calculation on the server (by using a product or order ID of some kind), and maybe also add a shared secret or API key-like value to the parameters (eg `http://localhost:3000/payment?buyer_id=...&seller_id=...&order=...&token=SHAREDSTRING`). Also in production of course you'd want that to be an `https` URL. But besides that, sounds good to me!

If you want to discuss this further you could shoot me an email about it -- http://ryanfunduk.com/contact
