### ISSUE TITLE
'verification must be a hash'

### ISSUE THREAD

**Issue by rfunduk** [rfunduk/rails-stripe-connect-example#4]
In https://github.com/rfunduk/rails-stripe-connect-example/pull/1 and separately in IRC and a couple emails, it's been pointed out that you can't save a managed account due to this 'verification must be a hash' error.

Setting `legal_entity` to a fresh hash (pre stripe-ruby 1.20.2 you couldn't piecemeal update nested hashes except `metadata`) somehow caused `verification` to be sent as an empty string.

I'm going to re-work this so that it updates the hash piecemeal instead.

**Comment by rfunduk** [comment]
cc @mikeholford @amonks

Thanks for pointing this out and providing details! Let me know if this still doesn't work for you.

**Comment by mikeholford** [comment]
@rfunduk ahh makes sense thanks for covering that for me. That seems to have worked great and user details are updated. I am guessing it is normal though for stripe to still have the status down as `Unverified` until they have done the checks?

**Comment by rfunduk** [comment]
Yea verification will be asynchronous. Watch for an `account.updated` webhook for more `fields_needed` or a change to `transfers_enabled`, etc.

**Comment by mikeholford** [comment]
Awesome thanks again for the help. All sorted and verification working. :+1:
